### ISSUE TITLE
ログアウト後、戻るボタンで前の画面に戻れてしまう

### ISSUE THREAD

**Issue by im-cu** [ima-s/o-net#29]

**Comment by ima-s** [comment]
俺の環境ではそうはならない. 
ログアウト押した時にセッションをdestoryしてるからそんなことないと思うけど, その操作した時のログ貼ってくれる?

**Comment by im-cu** [comment]
ログはこうなのですが
＞＞＞サインアウト
Started GET "/entries/1" for 10.0.2.2 at 2017-11-04 11:24:00 +0000
Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by EntriesController#show as HTML
  Parameters: {"id"=>"1"}
  Entry Load (2.2ms)  SELECT  "entries".* FROM "entries" WHERE "entries"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
Completed 401 Unauthorized in 8ms (ActiveRecord: 2.2ms)

＞＞＞戻るボタンクリック(一度でも二度でも)
Started GET "/users/sign_in" for 10.0.2.2 at 2017-11-04 11:24:00 +0000
Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Devise::SessionsController#new as HTML
  Rendering devise/sessions/new.html.erb within layouts/application
  Rendered devise/shared/_links.html.erb (2.4ms)
  Rendered devise/sessions/new.html.erb within layouts/application (122.3ms)
Completed 200 OK in 1482ms (Views: 1478.8ms | ActiveRecord: 0.0ms)

実際の表示は
エントリー詳細画面→ログアウト→戻る一回でエントリー詳細画面が表示される
ホーム画面→ログアウト→戻る一回では表示変化なし→二、三回押すとエントリー詳細画面が表示される
その後リダイレクトや遷移をした場合はsession/newにちゃんと飛びます

**Comment by im-cu** [comment]
放置でいいかなとも思います笑

**Comment by ima-s** [comment]
>その後リダイレクトや遷移をした場合はsession/newにちゃんと飛びます
じゃあ放置でok
